/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GapRouteImport } from './routes/gap'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SignalsRouteImport } from './routes/signals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GapRoute = GapRouteImport.update({
  id: '/gap',
  path: '/gap',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gap': typeof GapRoute
  '/lab': typeof LabRoute
  '/memory': typeof MemoryRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/paper': typeof PaperRoute
  '/portfolio': typeof PortfolioRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/signals': typeof SignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gap': typeof GapRoute
  '/lab': typeof LabRoute
  '/memory': typeof MemoryRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/paper': typeof PaperRoute
  '/portfolio': typeof PortfolioRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/signals': typeof SignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gap': typeof GapRoute
  '/lab': typeof LabRoute
  '/memory': typeof MemoryRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/paper': typeof PaperRoute
  '/portfolio': typeof PortfolioRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/signals': typeof SignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gap'
    | '/lab'
    | '/memory'
    | '/more'
    | '/news'
    | '/paper'
    | '/portfolio'
    | '/research'
    | '/risk'
    | '/signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gap'
    | '/lab'
    | '/memory'
    | '/more'
    | '/news'
    | '/paper'
    | '/portfolio'
    | '/research'
    | '/risk'
    | '/signals'
  id:
    | '__root__'
    | '/'
    | '/gap'
    | '/lab'
    | '/memory'
    | '/more'
    | '/news'
    | '/paper'
    | '/portfolio'
    | '/research'
    | '/risk'
    | '/signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GapRoute: typeof GapRoute
  LabRoute: typeof LabRoute
  MemoryRoute: typeof MemoryRoute
  MoreRoute: typeof MoreRoute
  NewsRoute: typeof NewsRoute
  PaperRoute: typeof PaperRoute
  PortfolioRoute: typeof PortfolioRoute
  ResearchRoute: typeof ResearchRoute
  RiskRoute: typeof RiskRoute
  SignalsRoute: typeof SignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap': {
      id: '/gap'
      path: '/gap'
      fullPath: '/gap'
      preLoaderRoute: typeof GapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GapRoute: GapRoute,
  LabRoute: LabRoute,
  MemoryRoute: MemoryRoute,
  MoreRoute: MoreRoute,
  NewsRoute: NewsRoute,
  PaperRoute: PaperRoute,
  PortfolioRoute: PortfolioRoute,
  ResearchRoute: ResearchRoute,
  RiskRoute: RiskRoute,
  SignalsRoute: SignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
